#! /bin/bash

#
# This script creates the setup.sh script for the `common` directory.
# Usage:
#   > ./create_common_setup.sh
#

mkdir -p $COMMON_PREFIX
chmod -R 777 $COMMON_PREFIX/..
cd $COMMON_PREFIX
echo "# This file is automatically generated by luna_dependencies/Scripts/create_common_setup.sh." > setup.sh
# Includes a one-time-use-only guard to avoid repeatedly adding to these environment variables.
echo '[ -n "$LUNA_BASE_SETUP" ] && return || readonly LUNA_BASE_SETUP=1' >> setup.sh
echo "export COMMON_TAG=$COMMON_TAG" >> setup.sh
echo "export COMMON_PREFIX=$COMMON_PREFIX" >> setup.sh
# creation of the "current" link is not required, and cannot be done in a singularity container
echo 'ln -sfT $COMMON_PREFIX $COMMON_PREFIX/../current || true' >> setup.sh
echo 'export PATH=$COMMON_PREFIX/bin:$PATH' >> setup.sh
echo 'export LD_LIBRARY_PATH=$COMMON_PREFIX/lib:$LD_LIBRARY_PATH' >> setup.sh
echo 'source /usr/local/root/bin/thisroot.sh' >> setup.sh
