mkdir -p $COMMON_BUILD_PREFIX
chmod -R 777 $COMMON_BUILD_PREFIX/..
cd $COMMON_BUILD_PREFIX
echo "# This file is automatically generated by luna/Dependencies/Dockerfile." > setup.sh
echo '[ -n "$P8COMPUTE_COMMON_SETUP" ] && return || readonly P8COMPUTE_COMMON_SETUP=1' >> setup.sh
echo "export COMMON_TAG=$COMMON_TAG" >> setup.sh
echo "export COMMON_BUILD_PREFIX=$COMMON_BUILD_PREFIX" >> setup.sh
# creation of the "current" link is not required, and cannot be done in a singularity container
echo 'ln -sfT $COMMON_BUILD_PREFIX $COMMON_BUILD_PREFIX/../current || true' >> setup.sh
echo 'export PATH=$COMMON_BUILD_PREFIX/bin:$PATH' >> setup.sh
echo 'export LD_LIBRARY_PATH=$COMMON_BUILD_PREFIX/lib:$LD_LIBRARY_PATH' >> setup.sh
echo 'source /usr/local/root/bin/thisroot.sh' >> setup.sh
