
name: Build and Publish Template

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string

jobs:

  build-and-publish:

    name: Build and push the docker images

    runs-on: ubuntu-latest
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: project8/p8compute_dependencies
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build
        id: build
        uses: docker/build-push-action@v3
        env:
          COMMON_TAG: ${GITHUB_REF#refs/*/}
        with:
          context: .
          file: ${{ inputs.dir }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            img_repo=ubuntu
            img_tag=20.04
            common_tag=${{ env.COMMON_TAG }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          platforms: linux/amd64
          