name: Build p8compute_dependencies

on:
  push:
    branches: [ main, develop, feature/GHActions ]
    tags: 'v*.*.*'
    #paths:
    #  - Dependencies/Dockerfile

  pull_request:
    branches: [ main, develop ]
    paths:
      - Dependencies/Dockerfile

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repo   # not needed when using the Git context in build-and-push
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      #- name: Build the Docker image
      #  run: docker build . --file Dependencies/Dockerfile --tag p8compute_dependencies:test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: Dependencies/
          file: Dependencies/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: project8/p8compute_dependencies:test  # todo: how to make this depend on the tag for releases
          #platforms: linux/amd65,linux/arm64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

