name: Build p8compute_dependencies

on:
  push:
    branches: [ main, develop ]
    tags: ['v*.*.*']

  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repo   # not needed when using the Git context in build-and-push
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: driplineorg/dripline-python
          tag-sha: false
          tag-semver: |
            {{raw}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: setup_buildx
      - name: List platforms
        run: echo ${{ steps.setup_buildx.outputs.platforms }}
      #- name: Build the Docker image
      #  run: docker build . --file Dependencies/Dockerfile --tag p8compute_dependencies:test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v2
        with:
          context: Dependencies/
          file: Dependencies/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            img_repo=ubuntu
            img_tag=20.04
          tags: ${{ steps.docker_meta.outputs.tags }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
      - name: Image digest
        run: >
          echo ${{ steps.build_push.outputs.digest }}
