name: Build p8compute_dependencies

on:
  push:
    branches: [ main, develop, feature/GHActions ]
    tags: 'v*.*.*'
    paths:
      - Dependencies/Dockerfile

  pull_request:
    branches: [ main, develop ]
    paths:
      - Dependencies/Dockerfile

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      #- name: Checkout the repo   # not needed when using the Git context in build-and-push
      #  uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #- name: Build the Docker image
      #  run: docker build . --file Dependencies/Dockerfile --tag p8compute_dependencies:test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Dependencies/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: project8/p8compute_dependencies:test  # todo: how to make this depend on the tag for releases
          #platforms: ...

